// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/dogmatiq/primo/internal/test/accessor/opaque.proto

package accessor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpaqueOneOf struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Group isOpaqueOneOf_Group    `protobuf_oneof:"group"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpaqueOneOf) Reset() {
	*x = OpaqueOneOf{}
	mi := &file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueOneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueOneOf) ProtoMessage() {}

func (x *OpaqueOneOf) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpaqueOneOf) GetFieldA() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldA); ok {
			return x.FieldA
		}
	}
	return 0
}

func (x *OpaqueOneOf) GetFieldB() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldB); ok {
			return x.FieldB
		}
	}
	return 0
}

func (x *OpaqueOneOf) GetFieldC() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldC); ok {
			return x.FieldC
		}
	}
	return ""
}

func (x *OpaqueOneOf) SetFieldA(v int32) {
	x.xxx_hidden_Group = &opaqueOneOf_FieldA{v}
}

func (x *OpaqueOneOf) SetFieldB(v int32) {
	x.xxx_hidden_Group = &opaqueOneOf_FieldB{v}
}

func (x *OpaqueOneOf) SetFieldC(v string) {
	x.xxx_hidden_Group = &opaqueOneOf_FieldC{v}
}

func (x *OpaqueOneOf) HasGroup() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Group != nil
}

func (x *OpaqueOneOf) HasFieldA() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldA)
	return ok
}

func (x *OpaqueOneOf) HasFieldB() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldB)
	return ok
}

func (x *OpaqueOneOf) HasFieldC() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldC)
	return ok
}

func (x *OpaqueOneOf) ClearGroup() {
	x.xxx_hidden_Group = nil
}

func (x *OpaqueOneOf) ClearFieldA() {
	if _, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldA); ok {
		x.xxx_hidden_Group = nil
	}
}

func (x *OpaqueOneOf) ClearFieldB() {
	if _, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldB); ok {
		x.xxx_hidden_Group = nil
	}
}

func (x *OpaqueOneOf) ClearFieldC() {
	if _, ok := x.xxx_hidden_Group.(*opaqueOneOf_FieldC); ok {
		x.xxx_hidden_Group = nil
	}
}

const OpaqueOneOf_Group_not_set_case case_OpaqueOneOf_Group = 0
const OpaqueOneOf_FieldA_case case_OpaqueOneOf_Group = 1
const OpaqueOneOf_FieldB_case case_OpaqueOneOf_Group = 2
const OpaqueOneOf_FieldC_case case_OpaqueOneOf_Group = 3

func (x *OpaqueOneOf) WhichGroup() case_OpaqueOneOf_Group {
	if x == nil {
		return OpaqueOneOf_Group_not_set_case
	}
	switch x.xxx_hidden_Group.(type) {
	case *opaqueOneOf_FieldA:
		return OpaqueOneOf_FieldA_case
	case *opaqueOneOf_FieldB:
		return OpaqueOneOf_FieldB_case
	case *opaqueOneOf_FieldC:
		return OpaqueOneOf_FieldC_case
	default:
		return OpaqueOneOf_Group_not_set_case
	}
}

type OpaqueOneOf_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Group:
	FieldA *int32
	FieldB *int32
	FieldC *string
	// -- end of xxx_hidden_Group
}

func (b0 OpaqueOneOf_builder) Build() *OpaqueOneOf {
	m0 := &OpaqueOneOf{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FieldA != nil {
		x.xxx_hidden_Group = &opaqueOneOf_FieldA{*b.FieldA}
	}
	if b.FieldB != nil {
		x.xxx_hidden_Group = &opaqueOneOf_FieldB{*b.FieldB}
	}
	if b.FieldC != nil {
		x.xxx_hidden_Group = &opaqueOneOf_FieldC{*b.FieldC}
	}
	return m0
}

type case_OpaqueOneOf_Group protoreflect.FieldNumber

func (x case_OpaqueOneOf_Group) String() string {
	md := file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOpaqueOneOf_Group interface {
	isOpaqueOneOf_Group()
}

type opaqueOneOf_FieldA struct {
	FieldA int32 `protobuf:"varint,1,opt,name=field_a,json=fieldA,oneof"`
}

type opaqueOneOf_FieldB struct {
	FieldB int32 `protobuf:"varint,2,opt,name=field_b,json=fieldB,oneof"`
}

type opaqueOneOf_FieldC struct {
	FieldC string `protobuf:"bytes,3,opt,name=field_c,json=fieldC,oneof"`
}

func (*opaqueOneOf_FieldA) isOpaqueOneOf_Group() {}

func (*opaqueOneOf_FieldB) isOpaqueOneOf_Group() {}

func (*opaqueOneOf_FieldC) isOpaqueOneOf_Group() {}

var File_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_rawDesc = "" +
	"\n" +
	"=github.com/dogmatiq/primo/internal/test/accessor/opaque.proto\x12\x13primo.test.mutators\"g\n" +
	"\vOpaqueOneOf\x12\x19\n" +
	"\afield_a\x18\x01 \x01(\x05H\x00R\x06fieldA\x12\x19\n" +
	"\afield_b\x18\x02 \x01(\x05H\x00R\x06fieldB\x12\x19\n" +
	"\afield_c\x18\x03 \x01(\tH\x00R\x06fieldCB\a\n" +
	"\x05groupB2Z0github.com/dogmatiq/primo/internal/test/accessorb\beditionsp\xe9\a"

var file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_goTypes = []any{
	(*OpaqueOneOf)(nil), // 0: primo.test.mutators.OpaqueOneOf
}
var file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto != nil {
		return
	}
	file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_msgTypes[0].OneofWrappers = []any{
		(*opaqueOneOf_FieldA)(nil),
		(*opaqueOneOf_FieldB)(nil),
		(*opaqueOneOf_FieldC)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_accessor_opaque_proto_depIdxs = nil
}
