// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: github.com/dogmatiq/primo/internal/test/formatting/formatting.proto

package formatting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stringable has a hand-written AsString() method, exercising the %s/%q
// override in the generated Format() method.
type Stringable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stringable) Reset() {
	*x = Stringable{}
	mi := &file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stringable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stringable) ProtoMessage() {}

func (x *Stringable) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stringable.ProtoReflect.Descriptor instead.
func (*Stringable) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescGZIP(), []int{0}
}

func (x *Stringable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Plain has no AsString() method, exercising the transparency of the generated
// Format() method.
type Plain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plain) Reset() {
	*x = Plain{}
	mi := &file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plain) ProtoMessage() {}

func (x *Plain) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plain.ProtoReflect.Descriptor instead.
func (*Plain) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescGZIP(), []int{1}
}

func (x *Plain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Panicky has AsString() and GoString() methods that always panic, exercising
// the panic-recovery behavior of the generated Format() method.
type Panicky struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Panicky) Reset() {
	*x = Panicky{}
	mi := &file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Panicky) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Panicky) ProtoMessage() {}

func (x *Panicky) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Panicky.ProtoReflect.Descriptor instead.
func (*Panicky) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescGZIP(), []int{2}
}

func (x *Panicky) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// NilSafe has AsString() and GoString() methods that handle a nil receiver
// themselves, exercising the generated Format() method's ability to call
// through to a nil-tolerant implementation instead of recovering from a panic.
type NilSafe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NilSafe) Reset() {
	*x = NilSafe{}
	mi := &file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NilSafe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NilSafe) ProtoMessage() {}

func (x *NilSafe) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NilSafe.ProtoReflect.Descriptor instead.
func (*NilSafe) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescGZIP(), []int{3}
}

func (x *NilSafe) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDesc = "" +
	"\n" +
	"Cgithub.com/dogmatiq/primo/internal/test/formatting/formatting.proto\x12\x15primo.test.formatting\"\"\n" +
	"\n" +
	"Stringable\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1d\n" +
	"\x05Plain\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1f\n" +
	"\aPanicky\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1f\n" +
	"\aNilSafe\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB4Z2github.com/dogmatiq/primo/internal/test/formattingb\x06proto3"

var (
	file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescData []byte
)

func file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_goTypes = []any{
	(*Stringable)(nil), // 0: primo.test.formatting.Stringable
	(*Plain)(nil),      // 1: primo.test.formatting.Plain
	(*Panicky)(nil),    // 2: primo.test.formatting.Panicky
	(*NilSafe)(nil),    // 3: primo.test.formatting.NilSafe
}
var file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_formatting_formatting_proto_depIdxs = nil
}
