// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: github.com/dogmatiq/primo/internal/test/mutators/test.proto

package mutators

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enumeration int32

const (
	Enumeration_ENUMERATION_UNKNOWN Enumeration = 0
)

// Enum value maps for Enumeration.
var (
	Enumeration_name = map[int32]string{
		0: "ENUMERATION_UNKNOWN",
	}
	Enumeration_value = map[string]int32{
		"ENUMERATION_UNKNOWN": 0,
	}
)

func (x Enumeration) Enum() *Enumeration {
	p := new(Enumeration)
	*p = x
	return p
}

func (x Enumeration) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enumeration) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_enumTypes[0].Descriptor()
}

func (Enumeration) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_enumTypes[0]
}

func (x Enumeration) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enumeration.Descriptor instead.
func (Enumeration) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to GroupA:
	//
	//	*Message_FieldA1
	//	*Message_FieldA2
	//	*Message_FieldA3
	GroupA isMessage_GroupA `protobuf_oneof:"group_a"`
	// Types that are assignable to GroupB:
	//
	//	*Message_FieldB1
	//	*Message_FieldB2
	//	*Message_FieldB3
	GroupB isMessage_GroupB `protobuf_oneof:"group_b"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetGroupA() isMessage_GroupA {
	if m != nil {
		return m.GroupA
	}
	return nil
}

func (x *Message) GetFieldA1() *Value {
	if x, ok := x.GetGroupA().(*Message_FieldA1); ok {
		return x.FieldA1
	}
	return nil
}

func (x *Message) GetFieldA2() *Value {
	if x, ok := x.GetGroupA().(*Message_FieldA2); ok {
		return x.FieldA2
	}
	return nil
}

func (x *Message) GetFieldA3() string {
	if x, ok := x.GetGroupA().(*Message_FieldA3); ok {
		return x.FieldA3
	}
	return ""
}

func (m *Message) GetGroupB() isMessage_GroupB {
	if m != nil {
		return m.GroupB
	}
	return nil
}

func (x *Message) GetFieldB1() *timestamppb.Timestamp {
	if x, ok := x.GetGroupB().(*Message_FieldB1); ok {
		return x.FieldB1
	}
	return nil
}

func (x *Message) GetFieldB2() int32 {
	if x, ok := x.GetGroupB().(*Message_FieldB2); ok {
		return x.FieldB2
	}
	return 0
}

func (x *Message) GetFieldB3() Enumeration {
	if x, ok := x.GetGroupB().(*Message_FieldB3); ok {
		return x.FieldB3
	}
	return Enumeration_ENUMERATION_UNKNOWN
}

type isMessage_GroupA interface {
	isMessage_GroupA()
}

type Message_FieldA1 struct {
	FieldA1 *Value `protobuf:"bytes,1,opt,name=field_a1,json=fieldA1,proto3,oneof"`
}

type Message_FieldA2 struct {
	FieldA2 *Value `protobuf:"bytes,2,opt,name=field_a2,json=fieldA2,proto3,oneof"`
}

type Message_FieldA3 struct {
	FieldA3 string `protobuf:"bytes,3,opt,name=field_a3,json=fieldA3,proto3,oneof"`
}

func (*Message_FieldA1) isMessage_GroupA() {}

func (*Message_FieldA2) isMessage_GroupA() {}

func (*Message_FieldA3) isMessage_GroupA() {}

type isMessage_GroupB interface {
	isMessage_GroupB()
}

type Message_FieldB1 struct {
	FieldB1 *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=field_b1,json=fieldB1,proto3,oneof"`
}

type Message_FieldB2 struct {
	FieldB2 int32 `protobuf:"varint,5,opt,name=field_b2,json=fieldB2,proto3,oneof"`
}

type Message_FieldB3 struct {
	FieldB3 Enumeration `protobuf:"varint,6,opt,name=field_b3,json=fieldB3,proto3,enum=primo.test.Enumeration,oneof"`
}

func (*Message_FieldB1) isMessage_GroupB() {}

func (*Message_FieldB2) isMessage_GroupB() {}

func (*Message_FieldB3) isMessage_GroupB() {}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescGZIP(), []int{1}
}

var File_github_com_dogmatiq_primo_internal_test_mutators_test_proto protoreflect.FileDescriptor

var file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x67,
	0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x72, 0x69, 0x6d, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x02, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x61, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x6f,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x07, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x41, 0x31, 0x12, 0x2e, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x61, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x6f,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x07, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x41, 0x32, 0x12, 0x1b, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x61, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x41, 0x33, 0x12, 0x37, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x31, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x48, 0x01, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x31, 0x12, 0x1b, 0x0a, 0x08,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01,
	0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x32, 0x12, 0x34, 0x0a, 0x08, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x62, 0x33, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72,
	0x69, 0x6d, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x33, 0x42,
	0x09, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x26,
	0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a,
	0x13, 0x45, 0x4e, 0x55, 0x4d, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x70, 0x72,
	0x69, 0x6d, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescData = file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDesc
)

func file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescData)
	})
	return file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_goTypes = []interface{}{
	(Enumeration)(0),              // 0: primo.test.Enumeration
	(*Message)(nil),               // 1: primo.test.Message
	(*Value)(nil),                 // 2: primo.test.Value
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_depIdxs = []int32{
	2, // 0: primo.test.Message.field_a1:type_name -> primo.test.Value
	2, // 1: primo.test.Message.field_a2:type_name -> primo.test.Value
	3, // 2: primo.test.Message.field_b1:type_name -> google.protobuf.Timestamp
	0, // 3: primo.test.Message.field_b3:type_name -> primo.test.Enumeration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_mutators_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_FieldA1)(nil),
		(*Message_FieldA2)(nil),
		(*Message_FieldA3)(nil),
		(*Message_FieldB1)(nil),
		(*Message_FieldB2)(nil),
		(*Message_FieldB3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_mutators_test_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_rawDesc = nil
	file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_mutators_test_proto_depIdxs = nil
}
