package formatting

import (
	"github.com/dave/jennifer/jen"
	"github.com/dogmatiq/primo/internal/generator/internal/scope"
)

// Generate generates a Format() method for each message type, allowing messages
// to be formatted with functions from the [fmt] package.
func Generate(code *jen.File, f *scope.File) error {
	for _, m := range f.Messages() {
		generateFormat(code, m)
	}

	return nil
}

// generateFormat generates a Format() method for the message.
func generateFormat(code *jen.File, m *scope.Message) {
	code.Comment("Format formats x according to the given [fmt] verb.")
	code.Comment("")
	code.Comment("It implements [fmt.Formatter], taking precedence over the String() method")
	code.Comment("generated by the Protocol Buffers compiler.")
	code.Comment("")
	code.Comment("For the %s and %q verbs it uses the string returned by x.AsString() if x")
	code.Comment("provides such a method. For the %#v verb it uses the string returned by")
	code.Comment("x.GoString() if x provides such a method. Otherwise it formats x as though this")
	code.Comment("method were not defined.")
	code.Comment("")
	code.Comment("AsString() and GoString() are called even when x is nil, since some message")
	code.Comment("types handle a nil receiver themselves. If either method panics, the panic is")
	code.Comment("formatted the same way the fmt package formats a panicking String() method.")

	code.
		Func().
		Params(
			jen.Id("x").Op("*").Id(m.GoTypeName),
		).
		Id("Format").
		Params(
			jen.Id("f").Qual("fmt", "State"),
			jen.Id("verb").Rune(),
		).
		Block(
			jen.
				Id("format").
				Op(":=").
				Qual("fmt", "FormatString").
				Call(jen.Id("f"), jen.Id("verb")),
			jen.Line(),

			// When formatting as a string, prefer a caller-provided AsString()
			// method if the type implements one.
			jen.
				If(
					jen.Id("verb").Op("==").LitRune('s').
						Op("||").
						Id("verb").Op("==").LitRune('q'),
				).
				BlockFunc(func(c *jen.Group) {
					c.
						If(
							jen.
								List(jen.Id("s"), jen.Id("ok")).
								Op(":=").
								Id("any").Call(jen.Id("x")).
								Assert(
									jen.Interface(
										jen.Id("AsString").Params().Add(jen.String()),
									),
								).
								Op(";").
								Id("ok"),
						).
						BlockFunc(func(c *jen.Group) {
							c.
								List(jen.Id("result"), jen.Id("ok")).
								Op(":=").
								Add(wrapWithPanicRecovery("AsString", jen.Id("s").Dot("AsString").Call()))
							c.
								If(jen.Id("ok")).
								Block(
									jen.Qual("fmt", "Fprintf").Call(jen.Id("f"), jen.Id("format"), jen.Id("result")),
								).
								Else().
								If(jen.Id("x").Op("==").Nil()).
								Block(
									jen.Qual("fmt", "Fprint").Call(jen.Id("f"), jen.Lit("<nil>")),
								).
								Else().
								Block(
									jen.Qual("fmt", "Fprint").Call(jen.Id("f"), jen.Id("result")),
								)
							c.Return()
						})
				}),
			jen.Line(),

			// The %#v verb corresponds to fmt's use of [fmt.GoStringer]; every
			// other verb handled here reproduces the behavior of the String()
			// method, which is how the fmt package formats a [fmt.Stringer].
			// Unlike the GoStringer check, this applies regardless of the '#'
			// flag, since fmt only treats '#' as selecting Go-syntax mode for the
			// %v verb.
			jen.
				If(
					jen.Id("verb").Op("==").LitRune('v').
						Op("&&").
						Id("f").Dot("Flag").Call(jen.LitRune('#')),
				).
				BlockFunc(func(c *jen.Group) {
					c.
						If(
							jen.
								List(jen.Id("s"), jen.Id("ok")).
								Op(":=").
								Id("any").Call(jen.Id("x")).
								Assert(
									jen.Interface(
										jen.Id("GoString").Params().Add(jen.String()),
									),
								).
								Op(";").
								Id("ok"),
						).
						BlockFunc(func(c *jen.Group) {
							c.
								List(jen.Id("result"), jen.Id("ok")).
								Op(":=").
								Add(wrapWithPanicRecovery("GoString", jen.Id("s").Dot("GoString").Call()))
							// GoString() results are printed unadorned (as with the
							// %s verb), matching fmt.GoStringer's contract.
							c.
								If(jen.Id("ok")).
								Block(
									jen.
										Qual("fmt", "Fprintf").
										Call(
											jen.Id("f"),
											jen.Qual("fmt", "FormatString").Call(jen.Id("f"), jen.LitRune('s')),
											jen.Id("result"),
										),
								).
								Else().
								If(jen.Id("x").Op("==").Nil()).
								Block(
									jen.Qual("fmt", "Fprint").Call(jen.Id("f"), jen.Lit("<nil>")),
								).
								Else().
								Block(
									jen.Qual("fmt", "Fprint").Call(jen.Id("f"), jen.Id("result")),
								)
							c.Return()
						})
				}).
				Else().
				BlockFunc(func(c *jen.Group) {
					c.
						Switch(jen.Id("verb")).
						Block(
							jen.
								Case(
									jen.LitRune('v'),
									jen.LitRune('s'),
									jen.LitRune('x'),
									jen.LitRune('X'),
									jen.LitRune('q'),
								).
								Block(
									jen.
										Qual("fmt", "Fprintf").
										Call(
											jen.Id("f"),
											jen.Id("format"),
											jen.Id("x").Dot("String").Call(),
										),
									jen.Return(),
								),
						)
				}),
			jen.Line(),

			// Fall back to the default formatting behavior. A new type with the
			// same structure as x but none of its methods avoids recursing into
			// this Format() method. It shares the name of the real type so that
			// the %#v verb still prints the correct type name.
			jen.Type().Id("realType").Op("=").Id(m.GoTypeName),
			jen.Type().Id(m.GoTypeName).Id("realType"),
			jen.
				Qual("fmt", "Fprintf").
				Call(
					jen.Id("f"),
					jen.Id("format"),
					jen.Params(jen.Op("*").Id(m.GoTypeName)).Call(jen.Id("x")),
				),
		)
}

// wrapWithPanicRecovery returns an immediately-invoked function literal that
// evaluates call and returns its result, recovering from a panic into a
// "%!verb(PANIC=method method: value)" marker, matching how fmt formats a
// panicking Stringer.
func wrapWithPanicRecovery(method string, call jen.Code) jen.Code {
	return jen.
		Func().
		Params().
		Params(
			jen.Id("result").String(),
			jen.Id("ok").Bool(),
		).
		Block(
			jen.
				Defer().
				Func().
				Params().
				Block(
					jen.
						If(
							jen.Id("r").Op(":=").Recover().
								Op(";").
								Id("r").Op("!=").Nil(),
						).
						Block(
							jen.
								Id("result").
								Op("=").
								Qual("fmt", "Sprintf").
								Call(
									jen.Lit("%%!%c(PANIC="+method+" method: %v)"),
									jen.Id("verb"),
									jen.Id("r"),
								),
						),
				).
				Call(),
			jen.Return(call, jen.True()),
		).
		Call()
}
