package formatting

import (
	"github.com/dave/jennifer/jen"
	"github.com/dogmatiq/primo/internal/generator/internal/scope"
)

// Generate generates a Format() method for each message type, allowing messages
// to be formatted with functions from the [fmt] package.
func Generate(code *jen.File, f *scope.File) error {
	for _, m := range f.Messages() {
		generateFormat(code, m)
	}

	return nil
}

// generateFormat generates a Format() method for the message.
func generateFormat(code *jen.File, m *scope.Message) {
	code.Comment("Format formats x according to the given [fmt] verb.")
	code.Comment("")
	code.Comment("It implements [fmt.Formatter], taking precedence over the String() method")
	code.Comment("generated by the Protocol Buffers compiler.")
	code.Comment("")
	code.Comment("For the %s and %q verbs it uses the string returned by x.AsString() if x")
	code.Comment("provides such a method. For the %#v verb it uses the string returned by")
	code.Comment("x.GoString() if x provides such a method. Otherwise it formats x as though this")
	code.Comment("method were not defined. A nil x never calls AsString() or GoString(), falling")
	code.Comment("through to the default behavior for the verb.")

	code.
		Func().
		Params(
			jen.Id("x").Op("*").Id(m.GoTypeName),
		).
		Id("Format").
		Params(
			jen.Id("f").Qual("fmt", "State"),
			jen.Id("verb").Rune(),
		).
		Block(
			jen.
				Id("format").
				Op(":=").
				Qual("fmt", "FormatString").
				Call(jen.Id("f"), jen.Id("verb")),
			jen.Line(),

			// When formatting a non-nil value as a string, prefer a
			// caller-provided AsString() method if the type implements one. The
			// nil check guards against AsString() implementations that
			// dereference the receiver; nil values fall through to String().
			jen.
				If(
					jen.Id("verb").Op("==").LitRune('s').
						Op("||").
						Id("verb").Op("==").LitRune('q'),
				).
				BlockFunc(func(c *jen.Group) {
					c.
						If(jen.Id("x").Op("!=").Nil()).
						Block(
							jen.
								If(
									jen.
										List(jen.Id("s"), jen.Id("ok")).
										Op(":=").
										Id("any").Call(jen.Id("x")).
										Assert(
											jen.Interface(
												jen.Id("AsString").Params().Add(jen.String()),
											),
										).
										Op(";").
										Id("ok"),
								).
								Block(
									jen.
										Qual("fmt", "Fprintf").
										Call(
											jen.Id("f"),
											jen.Id("format"),
											jen.Id("s").Dot("AsString").Call(),
										),
									jen.Return(),
								),
						)
				}),
			jen.Line(),

			// The %#v verb corresponds to fmt's use of [fmt.GoStringer]; every
			// other verb handled here reproduces the behavior of the String()
			// method, which is how the fmt package formats a [fmt.Stringer].
			// Unlike the GoStringer check, this applies regardless of the '#'
			// flag, since fmt only treats '#' as selecting Go-syntax mode for the
			// %v verb.
			jen.
				If(
					jen.Id("verb").Op("==").LitRune('v').
						Op("&&").
						Id("f").Dot("Flag").Call(jen.LitRune('#')),
				).
				BlockFunc(func(c *jen.Group) {
					c.
						If(jen.Id("x").Op("!=").Nil()).
						Block(
							jen.
								If(
									jen.
										List(jen.Id("s"), jen.Id("ok")).
										Op(":=").
										Id("any").Call(jen.Id("x")).
										Assert(
											jen.Interface(
												jen.Id("GoString").Params().Add(jen.String()),
											),
										).
										Op(";").
										Id("ok"),
								).
								Block(
									// GoString() results are printed unadorned (as
									// with the %s verb), matching fmt.GoStringer's
									// contract; the %#v format string is not reused
									// here since it would re-quote the string.
									jen.
										Qual("fmt", "Fprintf").
										Call(
											jen.Id("f"),
											jen.Qual("fmt", "FormatString").Call(jen.Id("f"), jen.LitRune('s')),
											jen.Id("s").Dot("GoString").Call(),
										),
									jen.Return(),
								),
						)
				}).
				Else().
				BlockFunc(func(c *jen.Group) {
					c.
						Switch(jen.Id("verb")).
						Block(
							jen.
								Case(
									jen.LitRune('v'),
									jen.LitRune('s'),
									jen.LitRune('x'),
									jen.LitRune('X'),
									jen.LitRune('q'),
								).
								Block(
									jen.
										Qual("fmt", "Fprintf").
										Call(
											jen.Id("f"),
											jen.Id("format"),
											jen.Id("x").Dot("String").Call(),
										),
									jen.Return(),
								),
						)
				}),
			jen.Line(),

			// Fall back to the default formatting behavior. A new type with the
			// same structure as x but none of its methods avoids recursing into
			// this Format() method. It shares the name of the real type so that
			// the %#v verb still prints the correct type name.
			jen.Type().Id("realType").Op("=").Id(m.GoTypeName),
			jen.Type().Id(m.GoTypeName).Id("realType"),
			jen.
				Qual("fmt", "Fprintf").
				Call(
					jen.Id("f"),
					jen.Id("format"),
					jen.Params(jen.Op("*").Id(m.GoTypeName)).Call(jen.Id("x")),
				),
		)
}
