package scope

import (
	"strings"

	"github.com/dave/jennifer/jen"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Field encapsulates information about a single field within a message.
type Field struct {
	Message     *Message
	Descriptor  *descriptorpb.FieldDescriptorProto
	OneOfOption *OneOfOption

	// GoIdentifiers contains the Go identifiers for this field as generated by
	// protoc-gen-go. Identifiers that do not exist for the current API level or
	// presence semantics are empty.
	GoIdentifiers struct {
		// Base is always set. It is the exported Go name derived from the
		// proto field name (e.g. "FieldA") and serves as the base for all
		// primo-generated names such as "WithFieldA" or "SetFieldA".
		Base string

		// ExportedField is the name of the exported struct field on the message
		// type. For discrete fields it matches Base; for oneof option
		// fields it is the group field name (e.g. "Group"). Empty for opaque
		// API messages, which have no exported struct fields.
		ExportedField string

		// HasMethod is the name of the HasXxx method, e.g. "HasFieldA".
		// Only set for opaque API messages with explicit presence; empty for
		// open API messages and for implicit-presence fields.
		HasMethod string

		// GetMethod is the name of the GetXxx method, e.g. "GetFieldA".
		// Only set for opaque API messages; empty for open API.
		GetMethod string

		// SetMethod is the name of the SetXxx method, e.g. "SetFieldA".
		// Only set for opaque API messages; empty for open API.
		SetMethod string
	}
}

// GoType returns the code snippet that refers to the type of the field.
func (f *Field) GoType() jen.Code {
	return f.Message.File.Request.typeExprForField(f.Descriptor, f.hasExplicitPresence())
}

// GoElemType returns the code snippet that refers to the element type of the
// field, stripping any pointer indirection that would otherwise be present for
// fields with explicit presence.
func (f *Field) GoElemType() jen.Code {
	return f.Message.File.Request.typeExprForField(f.Descriptor, false)
}

// hasExplicitPresence returns true if this field has explicit presence, meaning
// its Go type should be a pointer (e.g. *int32 rather than int32) to
// distinguish between "not set" and the zero value.
func (f *Field) hasExplicitPresence() bool {
	// Proto3 optional fields always have explicit presence.
	if f.Descriptor.GetProto3Optional() {
		return true
	}

	// Oneof fields track presence through the oneof discriminator, not through
	// a pointer type.
	if f.OneOfOption != nil {
		return false
	}

	// In editions 2023 and later the default field presence is EXPLICIT, so all
	// singular non-map non-repeated fields are pointer types unless overridden.
	fileFd := f.Message.File.Descriptor
	if fileFd.GetEdition() < descriptorpb.Edition_EDITION_2023 {
		return false
	}

	// A field-level features override to IMPLICIT takes precedence.
	if f.Descriptor.GetOptions().GetFeatures().GetFieldPresence() == descriptorpb.FeatureSet_IMPLICIT {
		return false
	}

	// A file-level features override to IMPLICIT applies to all fields unless
	// overridden at a narrower scope.
	if fileFd.GetOptions().GetFeatures().GetFieldPresence() == descriptorpb.FeatureSet_IMPLICIT {
		return false
	}

	return true
}

// fieldNameCollidesWithMethod returns true if the given field name should be
// suffixed with an underscore because it would otherwise collide with one of
// the automatically generated methods.
func fieldNameCollidesWithMethod(d *descriptorpb.FieldDescriptorProto) bool {
	switch strings.ToLower(d.GetName()) {
	case "string":
		return true
	default:
		return false
	}
}
