package scope

import "google.golang.org/protobuf/types/descriptorpb"

// OneOfGroup describes a one-of group.
type OneOfGroup struct {
	Message    *Message
	Descriptor *descriptorpb.OneofDescriptorProto
	Options    []*OneOfOption

	// GoIdentifiers contains the Go identifiers for this group as generated by
	// protoc-gen-go. Identifiers that do not exist for the current API level
	// are empty.
	GoIdentifiers struct {
		// Base is always set. It is the exported Go name derived from the
		// proto oneof name (e.g. "Group") and serves as the base for all
		// primo-generated names.
		Base string

		// ExportedField is the name of the exported struct field on the message
		// type, e.g. "Group". Only set for open API messages; empty for opaque.
		ExportedField string

		// GetMethod is the name of the GetXxx accessor method, e.g. "GetGroup".
		// Only set for open API messages; empty for opaque.
		GetMethod string

		// WhichMethod is the name of the WhichXxx method, e.g. "WhichGroup".
		// Only set for opaque API messages; empty for open.
		WhichMethod string
	}
}

// OneOfOption describes a field that is part of a one-of.
type OneOfOption struct {
	Group *OneOfGroup
	Field *Field

	// GoIdentifiers contains the Go identifiers for this option as generated by
	// protoc-gen-go. Identifiers that do not exist for the current API level
	// are empty.
	GoIdentifiers struct {
		// Base is always set. It is the exported Go name derived from the
		// proto field name (e.g. "ChoiceA") and serves as the base for all
		// primo-generated names such as "WithChoiceA" or "SetChoiceA". It is
		// also the field name within the open API discriminator struct.
		Base string

		// DiscriminatorType is the name of the open API discriminator type,
		// e.g. "Message_ChoiceA". Only set for open API messages; empty for
		// opaque. Non-trivially derived (includes message type prefix and
		// optional collision-avoidance suffix).
		DiscriminatorType string

		// HasMethod is the name of the HasXxx method, e.g. "HasChoiceA".
		// Only set for opaque API messages; empty for open.
		HasMethod string

		// GetMethod is the name of the GetXxx accessor method, e.g. "GetChoiceA".
		// Only set for opaque API messages; empty for open.
		GetMethod string

		// CaseConstant is the name of the opaque API case constant,
		// e.g. "Message_ChoiceA_case". Only set for opaque API messages; empty
		// for open. Non-trivially derived (includes message type prefix).
		CaseConstant string
	}
}
