// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: github.com/dogmatiq/primo/internal/test/builder/builder.proto

package builder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	FieldA int32                  `protobuf:"varint,1,opt,name=field_a,json=fieldA,proto3" json:"field_a,omitempty"`
	FieldB string                 `protobuf:"bytes,2,opt,name=field_b,json=fieldB,proto3" json:"field_b,omitempty"`
	// Types that are valid to be assigned to Group:
	//
	//	*Message_FieldC
	//	*Message_FieldD
	Group         isMessage_Group `protobuf_oneof:"group"`
	Nested        *Message_Nested `protobuf:"bytes,5,opt,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetFieldA() int32 {
	if x != nil {
		return x.FieldA
	}
	return 0
}

func (x *Message) GetFieldB() string {
	if x != nil {
		return x.FieldB
	}
	return ""
}

func (x *Message) GetGroup() isMessage_Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Message) GetFieldC() int32 {
	if x != nil {
		if x, ok := x.Group.(*Message_FieldC); ok {
			return x.FieldC
		}
	}
	return 0
}

func (x *Message) GetFieldD() int32 {
	if x != nil {
		if x, ok := x.Group.(*Message_FieldD); ok {
			return x.FieldD
		}
	}
	return 0
}

func (x *Message) GetNested() *Message_Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

type isMessage_Group interface {
	isMessage_Group()
}

type Message_FieldC struct {
	FieldC int32 `protobuf:"varint,3,opt,name=field_c,json=fieldC,proto3,oneof"`
}

type Message_FieldD struct {
	FieldD int32 `protobuf:"varint,4,opt,name=field_d,json=fieldD,proto3,oneof"`
}

func (*Message_FieldC) isMessage_Group() {}

func (*Message_FieldD) isMessage_Group() {}

type Message_Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         int32                  `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Nested) Reset() {
	*x = Message_Nested{}
	mi := &file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Nested) ProtoMessage() {}

func (x *Message_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Nested.ProtoReflect.Descriptor instead.
func (*Message_Nested) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Nested) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

var File_github_com_dogmatiq_primo_internal_test_builder_builder_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDesc = "" +
	"\n" +
	"=github.com/dogmatiq/primo/internal/test/builder/builder.proto\x12\x12primo.test.builder\"\xd6\x01\n" +
	"\aMessage\x12\x17\n" +
	"\afield_a\x18\x01 \x01(\x05R\x06fieldA\x12\x17\n" +
	"\afield_b\x18\x02 \x01(\tR\x06fieldB\x12\x19\n" +
	"\afield_c\x18\x03 \x01(\x05H\x00R\x06fieldC\x12\x19\n" +
	"\afield_d\x18\x04 \x01(\x05H\x00R\x06fieldD\x12:\n" +
	"\x06nested\x18\x05 \x01(\v2\".primo.test.builder.Message.NestedR\x06nested\x1a\x1e\n" +
	"\x06Nested\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x05R\x05fieldB\a\n" +
	"\x05groupB1Z/github.com/dogmatiq/primo/internal/test/builderb\x06proto3"

var (
	file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDescData []byte
)

func file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_goTypes = []any{
	(*Message)(nil),        // 0: primo.test.builder.Message
	(*Message_Nested)(nil), // 1: primo.test.builder.Message.Nested
}
var file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_depIdxs = []int32{
	1, // 0: primo.test.builder.Message.nested:type_name -> primo.test.builder.Message.Nested
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_builder_builder_proto != nil {
		return
	}
	file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_FieldC)(nil),
		(*Message_FieldD)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_builder_builder_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_builder_builder_proto_depIdxs = nil
}
