// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/dogmatiq/primo/internal/test/builder/opaque.proto

package builder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpaqueMessage is an opaque API message used to verify that primo's builder
// generator produces correct builders for opaque API messages.
type OpaqueMessage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FieldA      int32                  `protobuf:"varint,1,opt,name=field_a,json=fieldA"`
	xxx_hidden_FieldB      *string                `protobuf:"bytes,2,opt,name=field_b,json=fieldB"`
	xxx_hidden_Group       isOpaqueMessage_Group  `protobuf_oneof:"group"`
	xxx_hidden_Nested      *OpaqueMessage_Nested  `protobuf:"bytes,5,opt,name=nested"`
	xxx_hidden_FieldE      int32                  `protobuf:"varint,6,opt,name=field_e,json=fieldE"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OpaqueMessage) Reset() {
	*x = OpaqueMessage{}
	mi := &file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueMessage) ProtoMessage() {}

func (x *OpaqueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpaqueMessage) GetFieldA() int32 {
	if x != nil {
		return x.xxx_hidden_FieldA
	}
	return 0
}

func (x *OpaqueMessage) GetFieldB() string {
	if x != nil {
		if x.xxx_hidden_FieldB != nil {
			return *x.xxx_hidden_FieldB
		}
		return ""
	}
	return ""
}

func (x *OpaqueMessage) GetFieldC() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Group.(*opaqueMessage_FieldC); ok {
			return x.FieldC
		}
	}
	return 0
}

func (x *OpaqueMessage) GetFieldD() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Group.(*opaqueMessage_FieldD); ok {
			return x.FieldD
		}
	}
	return 0
}

func (x *OpaqueMessage) GetNested() *OpaqueMessage_Nested {
	if x != nil {
		return x.xxx_hidden_Nested
	}
	return nil
}

func (x *OpaqueMessage) GetFieldE() int32 {
	if x != nil {
		return x.xxx_hidden_FieldE
	}
	return 0
}

func (x *OpaqueMessage) SetFieldA(v int32) {
	x.xxx_hidden_FieldA = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *OpaqueMessage) SetFieldB(v string) {
	x.xxx_hidden_FieldB = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *OpaqueMessage) SetFieldC(v int32) {
	x.xxx_hidden_Group = &opaqueMessage_FieldC{v}
}

func (x *OpaqueMessage) SetFieldD(v int32) {
	x.xxx_hidden_Group = &opaqueMessage_FieldD{v}
}

func (x *OpaqueMessage) SetNested(v *OpaqueMessage_Nested) {
	x.xxx_hidden_Nested = v
}

func (x *OpaqueMessage) SetFieldE(v int32) {
	x.xxx_hidden_FieldE = v
}

func (x *OpaqueMessage) HasFieldA() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpaqueMessage) HasFieldB() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OpaqueMessage) HasGroup() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Group != nil
}

func (x *OpaqueMessage) HasFieldC() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Group.(*opaqueMessage_FieldC)
	return ok
}

func (x *OpaqueMessage) HasFieldD() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Group.(*opaqueMessage_FieldD)
	return ok
}

func (x *OpaqueMessage) HasNested() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nested != nil
}

func (x *OpaqueMessage) ClearFieldA() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FieldA = 0
}

func (x *OpaqueMessage) ClearFieldB() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FieldB = nil
}

func (x *OpaqueMessage) ClearGroup() {
	x.xxx_hidden_Group = nil
}

func (x *OpaqueMessage) ClearFieldC() {
	if _, ok := x.xxx_hidden_Group.(*opaqueMessage_FieldC); ok {
		x.xxx_hidden_Group = nil
	}
}

func (x *OpaqueMessage) ClearFieldD() {
	if _, ok := x.xxx_hidden_Group.(*opaqueMessage_FieldD); ok {
		x.xxx_hidden_Group = nil
	}
}

func (x *OpaqueMessage) ClearNested() {
	x.xxx_hidden_Nested = nil
}

const OpaqueMessage_Group_not_set_case case_OpaqueMessage_Group = 0
const OpaqueMessage_FieldC_case case_OpaqueMessage_Group = 3
const OpaqueMessage_FieldD_case case_OpaqueMessage_Group = 4

func (x *OpaqueMessage) WhichGroup() case_OpaqueMessage_Group {
	if x == nil {
		return OpaqueMessage_Group_not_set_case
	}
	switch x.xxx_hidden_Group.(type) {
	case *opaqueMessage_FieldC:
		return OpaqueMessage_FieldC_case
	case *opaqueMessage_FieldD:
		return OpaqueMessage_FieldD_case
	default:
		return OpaqueMessage_Group_not_set_case
	}
}

type OpaqueMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FieldA *int32
	FieldB *string
	// Fields of oneof xxx_hidden_Group:
	FieldC *int32
	FieldD *int32
	// -- end of xxx_hidden_Group
	Nested *OpaqueMessage_Nested
	// field_e uses implicit presence, so its Go type is int32 (not *int32)
	// even though the file-level default is EXPLICIT.
	FieldE int32
}

func (b0 OpaqueMessage_builder) Build() *OpaqueMessage {
	m0 := &OpaqueMessage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FieldA != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_FieldA = *b.FieldA
	}
	if b.FieldB != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_FieldB = b.FieldB
	}
	if b.FieldC != nil {
		x.xxx_hidden_Group = &opaqueMessage_FieldC{*b.FieldC}
	}
	if b.FieldD != nil {
		x.xxx_hidden_Group = &opaqueMessage_FieldD{*b.FieldD}
	}
	x.xxx_hidden_Nested = b.Nested
	x.xxx_hidden_FieldE = b.FieldE
	return m0
}

type case_OpaqueMessage_Group protoreflect.FieldNumber

func (x case_OpaqueMessage_Group) String() string {
	md := file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOpaqueMessage_Group interface {
	isOpaqueMessage_Group()
}

type opaqueMessage_FieldC struct {
	FieldC int32 `protobuf:"varint,3,opt,name=field_c,json=fieldC,oneof"`
}

type opaqueMessage_FieldD struct {
	FieldD int32 `protobuf:"varint,4,opt,name=field_d,json=fieldD,oneof"`
}

func (*opaqueMessage_FieldC) isOpaqueMessage_Group() {}

func (*opaqueMessage_FieldD) isOpaqueMessage_Group() {}

type OpaqueMessage_Nested struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Field       int32                  `protobuf:"varint,1,opt,name=field"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OpaqueMessage_Nested) Reset() {
	*x = OpaqueMessage_Nested{}
	mi := &file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueMessage_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueMessage_Nested) ProtoMessage() {}

func (x *OpaqueMessage_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpaqueMessage_Nested) GetField() int32 {
	if x != nil {
		return x.xxx_hidden_Field
	}
	return 0
}

func (x *OpaqueMessage_Nested) SetField(v int32) {
	x.xxx_hidden_Field = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *OpaqueMessage_Nested) HasField() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpaqueMessage_Nested) ClearField() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Field = 0
}

type OpaqueMessage_Nested_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Field *int32
}

func (b0 OpaqueMessage_Nested_builder) Build() *OpaqueMessage_Nested {
	m0 := &OpaqueMessage_Nested{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Field != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Field = *b.Field
	}
	return m0
}

var File_github_com_dogmatiq_primo_internal_test_builder_opaque_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_rawDesc = "" +
	"\n" +
	"<github.com/dogmatiq/primo/internal/test/builder/opaque.proto\x12\x12primo.test.builder\"\x82\x02\n" +
	"\rOpaqueMessage\x12\x17\n" +
	"\afield_a\x18\x01 \x01(\x05R\x06fieldA\x12\x17\n" +
	"\afield_b\x18\x02 \x01(\tR\x06fieldB\x12\x19\n" +
	"\afield_c\x18\x03 \x01(\x05H\x00R\x06fieldC\x12\x19\n" +
	"\afield_d\x18\x04 \x01(\x05H\x00R\x06fieldD\x12@\n" +
	"\x06nested\x18\x05 \x01(\v2(.primo.test.builder.OpaqueMessage.NestedR\x06nested\x12\x1e\n" +
	"\afield_e\x18\x06 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x06fieldE\x1a\x1e\n" +
	"\x06Nested\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x05R\x05fieldB\a\n" +
	"\x05groupB1Z/github.com/dogmatiq/primo/internal/test/builderb\beditionsp\xe9\a"

var file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_goTypes = []any{
	(*OpaqueMessage)(nil),        // 0: primo.test.builder.OpaqueMessage
	(*OpaqueMessage_Nested)(nil), // 1: primo.test.builder.OpaqueMessage.Nested
}
var file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_depIdxs = []int32{
	1, // 0: primo.test.builder.OpaqueMessage.nested:type_name -> primo.test.builder.OpaqueMessage.Nested
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_builder_opaque_proto != nil {
		return
	}
	file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_msgTypes[0].OneofWrappers = []any{
		(*opaqueMessage_FieldC)(nil),
		(*opaqueMessage_FieldD)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_builder_opaque_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_builder_opaque_proto_depIdxs = nil
}
