// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/dogmatiq/primo/internal/test/proto3optional/proto3optional.proto

package proto3optional

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_ERR         Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERR",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERR":         2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescGZIP(), []int{0}
}

// Message contains a mix of proto3 optional fields and a real oneof, to verify
// that optional fields are not misidentified as oneof members.
type Message struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Num    *int32                 `protobuf:"varint,1,opt,name=num,proto3,oneof" json:"num,omitempty"`
	Str    *string                `protobuf:"bytes,2,opt,name=str,proto3,oneof" json:"str,omitempty"`
	Flag   *bool                  `protobuf:"varint,3,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	Status *Status                `protobuf:"varint,4,opt,name=status,proto3,enum=primo.test.proto3optional.Status,oneof" json:"status,omitempty"`
	Child  *Message_Child         `protobuf:"bytes,5,opt,name=child,proto3,oneof" json:"child,omitempty"`
	// Types that are valid to be assigned to Choice:
	//
	//	*Message_ChoiceA
	//	*Message_ChoiceB
	Choice        isMessage_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetNum() int32 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

func (x *Message) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return ""
}

func (x *Message) GetFlag() bool {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return false
}

func (x *Message) GetStatus() Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Message) GetChild() *Message_Child {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *Message) GetChoice() isMessage_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *Message) GetChoiceA() string {
	if x != nil {
		if x, ok := x.Choice.(*Message_ChoiceA); ok {
			return x.ChoiceA
		}
	}
	return ""
}

func (x *Message) GetChoiceB() int32 {
	if x != nil {
		if x, ok := x.Choice.(*Message_ChoiceB); ok {
			return x.ChoiceB
		}
	}
	return 0
}

type isMessage_Choice interface {
	isMessage_Choice()
}

type Message_ChoiceA struct {
	ChoiceA string `protobuf:"bytes,6,opt,name=choice_a,json=choiceA,proto3,oneof"`
}

type Message_ChoiceB struct {
	ChoiceB int32 `protobuf:"varint,7,opt,name=choice_b,json=choiceB,proto3,oneof"`
}

func (*Message_ChoiceA) isMessage_Choice() {}

func (*Message_ChoiceB) isMessage_Choice() {}

type Message_Child struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Child) Reset() {
	*x = Message_Child{}
	mi := &file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Child) ProtoMessage() {}

func (x *Message_Child) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Child.ProtoReflect.Descriptor instead.
func (*Message_Child) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescGZIP(), []int{0, 0}
}

var File_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDesc = "" +
	"\n" +
	"Kgithub.com/dogmatiq/primo/internal/test/proto3optional/proto3optional.proto\x12\x19primo.test.proto3optional\"\xd0\x02\n" +
	"\aMessage\x12\x15\n" +
	"\x03num\x18\x01 \x01(\x05H\x01R\x03num\x88\x01\x01\x12\x15\n" +
	"\x03str\x18\x02 \x01(\tH\x02R\x03str\x88\x01\x01\x12\x17\n" +
	"\x04flag\x18\x03 \x01(\bH\x03R\x04flag\x88\x01\x01\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2!.primo.test.proto3optional.StatusH\x04R\x06status\x88\x01\x01\x12C\n" +
	"\x05child\x18\x05 \x01(\v2(.primo.test.proto3optional.Message.ChildH\x05R\x05child\x88\x01\x01\x12\x1b\n" +
	"\bchoice_a\x18\x06 \x01(\tH\x00R\achoiceA\x12\x1b\n" +
	"\bchoice_b\x18\a \x01(\x05H\x00R\achoiceB\x1a\a\n" +
	"\x05ChildB\b\n" +
	"\x06choiceB\x06\n" +
	"\x04_numB\x06\n" +
	"\x04_strB\a\n" +
	"\x05_flagB\t\n" +
	"\a_statusB\b\n" +
	"\x06_child*?\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x0e\n" +
	"\n" +
	"STATUS_ERR\x10\x02B8Z6github.com/dogmatiq/primo/internal/test/proto3optionalb\x06proto3"

var (
	file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescData []byte
)

func file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_goTypes = []any{
	(Status)(0),           // 0: primo.test.proto3optional.Status
	(*Message)(nil),       // 1: primo.test.proto3optional.Message
	(*Message_Child)(nil), // 2: primo.test.proto3optional.Message.Child
}
var file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_depIdxs = []int32{
	0, // 0: primo.test.proto3optional.Message.status:type_name -> primo.test.proto3optional.Status
	2, // 1: primo.test.proto3optional.Message.child:type_name -> primo.test.proto3optional.Message.Child
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto != nil {
		return
	}
	file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_ChoiceA)(nil),
		(*Message_ChoiceB)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_proto3optional_proto3optional_proto_depIdxs = nil
}
