// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: github.com/dogmatiq/primo/internal/test/exhaustiveswitch/enum.proto

package exhaustiveswitch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_UNKNOWN  Direction = 0
	Direction_LEFT     Direction = -1
	Direction_RIGHT    Direction = 1
	Direction_SINISTER Direction = -1
	Direction_DEXTER   Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0:  "UNKNOWN",
		-1: "LEFT",
		1:  "RIGHT",
		// Duplicate value: -1: "SINISTER",
		// Duplicate value: 1: "DEXTER",
	}
	Direction_value = map[string]int32{
		"UNKNOWN":  0,
		"LEFT":     -1,
		"RIGHT":    1,
		"SINISTER": -1,
		"DEXTER":   1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescGZIP(), []int{0}
}

type NestedEnum_Direction int32

const (
	NestedEnum_UNKNOWN  NestedEnum_Direction = 0
	NestedEnum_LEFT     NestedEnum_Direction = -1
	NestedEnum_RIGHT    NestedEnum_Direction = 1
	NestedEnum_SINISTER NestedEnum_Direction = -1
	NestedEnum_DEXTER   NestedEnum_Direction = 1
)

// Enum value maps for NestedEnum_Direction.
var (
	NestedEnum_Direction_name = map[int32]string{
		0:  "UNKNOWN",
		-1: "LEFT",
		1:  "RIGHT",
		// Duplicate value: -1: "SINISTER",
		// Duplicate value: 1: "DEXTER",
	}
	NestedEnum_Direction_value = map[string]int32{
		"UNKNOWN":  0,
		"LEFT":     -1,
		"RIGHT":    1,
		"SINISTER": -1,
		"DEXTER":   1,
	}
)

func (x NestedEnum_Direction) Enum() *NestedEnum_Direction {
	p := new(NestedEnum_Direction)
	*p = x
	return p
}

func (x NestedEnum_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NestedEnum_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_enumTypes[1].Descriptor()
}

func (NestedEnum_Direction) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_enumTypes[1]
}

func (x NestedEnum_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NestedEnum_Direction.Descriptor instead.
func (NestedEnum_Direction) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescGZIP(), []int{0, 0}
}

type NestedEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedEnum) Reset() {
	*x = NestedEnum{}
	mi := &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedEnum) ProtoMessage() {}

func (x *NestedEnum) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedEnum.ProtoReflect.Descriptor instead.
func (*NestedEnum) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescGZIP(), []int{0}
}

var File_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDesc = "" +
	"\n" +
	"Cgithub.com/dogmatiq/primo/internal/test/exhaustiveswitch/enum.proto\x12\x1bprimo.test.exhaustiveswitch\"k\n" +
	"\n" +
	"NestedEnum\"]\n" +
	"\tDirection\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\x04LEFT\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\t\n" +
	"\x05RIGHT\x10\x01\x12\x15\n" +
	"\bSINISTER\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\n" +
	"\n" +
	"\x06DEXTER\x10\x01\x1a\x02\x10\x01*]\n" +
	"\tDirection\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\x04LEFT\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\t\n" +
	"\x05RIGHT\x10\x01\x12\x15\n" +
	"\bSINISTER\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\n" +
	"\n" +
	"\x06DEXTER\x10\x01\x1a\x02\x10\x01B:Z8github.com/dogmatiq/primo/internal/test/exhaustiveswitchb\x06proto3"

var (
	file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescData []byte
)

func file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_goTypes = []any{
	(Direction)(0),            // 0: primo.test.exhaustiveswitch.Direction
	(NestedEnum_Direction)(0), // 1: primo.test.exhaustiveswitch.NestedEnum.Direction
	(*NestedEnum)(nil),        // 2: primo.test.exhaustiveswitch.NestedEnum
}
var file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_enum_proto_depIdxs = nil
}
