// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/dogmatiq/primo/internal/test/exhaustiveswitch/opaque.proto

package exhaustiveswitch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpaqueDirection int32

const (
	OpaqueDirection_OPAQUE_DIRECTION_UNSPECIFIED OpaqueDirection = 0
	OpaqueDirection_OPAQUE_DIRECTION_LEFT        OpaqueDirection = 1
	OpaqueDirection_OPAQUE_DIRECTION_RIGHT       OpaqueDirection = 2
)

// Enum value maps for OpaqueDirection.
var (
	OpaqueDirection_name = map[int32]string{
		0: "OPAQUE_DIRECTION_UNSPECIFIED",
		1: "OPAQUE_DIRECTION_LEFT",
		2: "OPAQUE_DIRECTION_RIGHT",
	}
	OpaqueDirection_value = map[string]int32{
		"OPAQUE_DIRECTION_UNSPECIFIED": 0,
		"OPAQUE_DIRECTION_LEFT":        1,
		"OPAQUE_DIRECTION_RIGHT":       2,
	}
)

func (x OpaqueDirection) Enum() *OpaqueDirection {
	p := new(OpaqueDirection)
	*p = x
	return p
}

func (x OpaqueDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpaqueDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_enumTypes[0].Descriptor()
}

func (OpaqueDirection) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_enumTypes[0]
}

func (x OpaqueDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OpaqueRecord struct {
	state                protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Operation isOpaqueRecord_Operation `protobuf_oneof:"operation"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OpaqueRecord) Reset() {
	*x = OpaqueRecord{}
	mi := &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueRecord) ProtoMessage() {}

func (x *OpaqueRecord) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpaqueRecord) GetIncrement() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*opaqueRecord_Increment); ok {
			return x.Increment
		}
	}
	return 0
}

func (x *OpaqueRecord) GetDecrement() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*opaqueRecord_Decrement); ok {
			return x.Decrement
		}
	}
	return 0
}

func (x *OpaqueRecord) GetLog() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*opaqueRecord_Log); ok {
			return x.Log
		}
	}
	return ""
}

func (x *OpaqueRecord) GetNamingCollision() *OpaqueRecord_NamingCollision {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*opaqueRecord_NamingCollision_); ok {
			return x.NamingCollision
		}
	}
	return nil
}

func (x *OpaqueRecord) SetIncrement(v int32) {
	x.xxx_hidden_Operation = &opaqueRecord_Increment{v}
}

func (x *OpaqueRecord) SetDecrement(v int32) {
	x.xxx_hidden_Operation = &opaqueRecord_Decrement{v}
}

func (x *OpaqueRecord) SetLog(v string) {
	x.xxx_hidden_Operation = &opaqueRecord_Log{v}
}

func (x *OpaqueRecord) SetNamingCollision(v *OpaqueRecord_NamingCollision) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &opaqueRecord_NamingCollision_{v}
}

func (x *OpaqueRecord) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *OpaqueRecord) HasIncrement() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*opaqueRecord_Increment)
	return ok
}

func (x *OpaqueRecord) HasDecrement() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*opaqueRecord_Decrement)
	return ok
}

func (x *OpaqueRecord) HasLog() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*opaqueRecord_Log)
	return ok
}

func (x *OpaqueRecord) HasNamingCollision() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*opaqueRecord_NamingCollision_)
	return ok
}

func (x *OpaqueRecord) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

func (x *OpaqueRecord) ClearIncrement() {
	if _, ok := x.xxx_hidden_Operation.(*opaqueRecord_Increment); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *OpaqueRecord) ClearDecrement() {
	if _, ok := x.xxx_hidden_Operation.(*opaqueRecord_Decrement); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *OpaqueRecord) ClearLog() {
	if _, ok := x.xxx_hidden_Operation.(*opaqueRecord_Log); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *OpaqueRecord) ClearNamingCollision() {
	if _, ok := x.xxx_hidden_Operation.(*opaqueRecord_NamingCollision_); ok {
		x.xxx_hidden_Operation = nil
	}
}

const OpaqueRecord_Operation_not_set_case case_OpaqueRecord_Operation = 0
const OpaqueRecord_Increment_case case_OpaqueRecord_Operation = 1
const OpaqueRecord_Decrement_case case_OpaqueRecord_Operation = 2
const OpaqueRecord_Log_case case_OpaqueRecord_Operation = 3
const OpaqueRecord_NamingCollision_case case_OpaqueRecord_Operation = 4

func (x *OpaqueRecord) WhichOperation() case_OpaqueRecord_Operation {
	if x == nil {
		return OpaqueRecord_Operation_not_set_case
	}
	switch x.xxx_hidden_Operation.(type) {
	case *opaqueRecord_Increment:
		return OpaqueRecord_Increment_case
	case *opaqueRecord_Decrement:
		return OpaqueRecord_Decrement_case
	case *opaqueRecord_Log:
		return OpaqueRecord_Log_case
	case *opaqueRecord_NamingCollision_:
		return OpaqueRecord_NamingCollision_case
	default:
		return OpaqueRecord_Operation_not_set_case
	}
}

type OpaqueRecord_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Operation:
	Increment       *int32
	Decrement       *int32
	Log             *string
	NamingCollision *OpaqueRecord_NamingCollision
	// -- end of xxx_hidden_Operation
}

func (b0 OpaqueRecord_builder) Build() *OpaqueRecord {
	m0 := &OpaqueRecord{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Increment != nil {
		x.xxx_hidden_Operation = &opaqueRecord_Increment{*b.Increment}
	}
	if b.Decrement != nil {
		x.xxx_hidden_Operation = &opaqueRecord_Decrement{*b.Decrement}
	}
	if b.Log != nil {
		x.xxx_hidden_Operation = &opaqueRecord_Log{*b.Log}
	}
	if b.NamingCollision != nil {
		x.xxx_hidden_Operation = &opaqueRecord_NamingCollision_{b.NamingCollision}
	}
	return m0
}

type case_OpaqueRecord_Operation protoreflect.FieldNumber

func (x case_OpaqueRecord_Operation) String() string {
	md := file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOpaqueRecord_Operation interface {
	isOpaqueRecord_Operation()
}

type opaqueRecord_Increment struct {
	Increment int32 `protobuf:"varint,1,opt,name=increment,oneof"`
}

type opaqueRecord_Decrement struct {
	Decrement int32 `protobuf:"varint,2,opt,name=decrement,oneof"`
}

type opaqueRecord_Log struct {
	Log string `protobuf:"bytes,3,opt,name=log,oneof"`
}

type opaqueRecord_NamingCollision_ struct {
	NamingCollision *OpaqueRecord_NamingCollision `protobuf:"bytes,4,opt,name=naming_collision,json=namingCollision,oneof"`
}

func (*opaqueRecord_Increment) isOpaqueRecord_Operation() {}

func (*opaqueRecord_Decrement) isOpaqueRecord_Operation() {}

func (*opaqueRecord_Log) isOpaqueRecord_Operation() {}

func (*opaqueRecord_NamingCollision_) isOpaqueRecord_Operation() {}

type OpaqueRecord_NamingCollision struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpaqueRecord_NamingCollision) Reset() {
	*x = OpaqueRecord_NamingCollision{}
	mi := &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueRecord_NamingCollision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueRecord_NamingCollision) ProtoMessage() {}

func (x *OpaqueRecord_NamingCollision) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type OpaqueRecord_NamingCollision_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 OpaqueRecord_NamingCollision_builder) Build() *OpaqueRecord_NamingCollision {
	m0 := &OpaqueRecord_NamingCollision{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_rawDesc = "" +
	"\n" +
	"Egithub.com/dogmatiq/primo/internal/test/exhaustiveswitch/opaque.proto\x12\x1bprimo.test.exhaustiveswitch\"\xea\x01\n" +
	"\fOpaqueRecord\x12\x1e\n" +
	"\tincrement\x18\x01 \x01(\x05H\x00R\tincrement\x12\x1e\n" +
	"\tdecrement\x18\x02 \x01(\x05H\x00R\tdecrement\x12\x12\n" +
	"\x03log\x18\x03 \x01(\tH\x00R\x03log\x12f\n" +
	"\x10naming_collision\x18\x04 \x01(\v29.primo.test.exhaustiveswitch.OpaqueRecord.NamingCollisionH\x00R\x0fnamingCollision\x1a\x11\n" +
	"\x0fNamingCollisionB\v\n" +
	"\toperation*j\n" +
	"\x0fOpaqueDirection\x12 \n" +
	"\x1cOPAQUE_DIRECTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPAQUE_DIRECTION_LEFT\x10\x01\x12\x1a\n" +
	"\x16OPAQUE_DIRECTION_RIGHT\x10\x02B:Z8github.com/dogmatiq/primo/internal/test/exhaustiveswitchb\beditionsp\xe9\a"

var file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_goTypes = []any{
	(OpaqueDirection)(0),                 // 0: primo.test.exhaustiveswitch.OpaqueDirection
	(*OpaqueRecord)(nil),                 // 1: primo.test.exhaustiveswitch.OpaqueRecord
	(*OpaqueRecord_NamingCollision)(nil), // 2: primo.test.exhaustiveswitch.OpaqueRecord.NamingCollision
}
var file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_depIdxs = []int32{
	2, // 0: primo.test.exhaustiveswitch.OpaqueRecord.naming_collision:type_name -> primo.test.exhaustiveswitch.OpaqueRecord.NamingCollision
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto != nil {
		return
	}
	file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_msgTypes[0].OneofWrappers = []any{
		(*opaqueRecord_Increment)(nil),
		(*opaqueRecord_Decrement)(nil),
		(*opaqueRecord_Log)(nil),
		(*opaqueRecord_NamingCollision_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_exhaustiveswitch_opaque_proto_depIdxs = nil
}
