// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: github.com/dogmatiq/primo/internal/test/mutator/collection.proto

package mutator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repeated      []int32                `protobuf:"varint,1,rep,packed,name=repeated,proto3" json:"repeated,omitempty"`
	Map           map[string]int32       `protobuf:"bytes,2,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Collection) GetRepeated() []int32 {
	if x != nil {
		return x.Repeated
	}
	return nil
}

func (x *Collection) GetMap() map[string]int32 {
	if x != nil {
		return x.Map
	}
	return nil
}

var File_github_com_dogmatiq_primo_internal_test_mutator_collection_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDesc = "" +
	"\n" +
	"@github.com/dogmatiq/primo/internal/test/mutator/collection.proto\x12\x13primo.test.mutators\"\x9c\x01\n" +
	"\n" +
	"Collection\x12\x1a\n" +
	"\brepeated\x18\x01 \x03(\x05R\brepeated\x12:\n" +
	"\x03map\x18\x02 \x03(\v2(.primo.test.mutators.Collection.MapEntryR\x03map\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B1Z/github.com/dogmatiq/primo/internal/test/mutatorb\x06proto3"

var (
	file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDescData []byte
)

func file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_goTypes = []any{
	(*Collection)(nil), // 0: primo.test.mutators.Collection
	nil,                // 1: primo.test.mutators.Collection.MapEntry
}
var file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_depIdxs = []int32{
	1, // 0: primo.test.mutators.Collection.map:type_name -> primo.test.mutators.Collection.MapEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_mutator_collection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_mutator_collection_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_mutator_collection_proto_depIdxs = nil
}
