// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/dogmatiq/primo/internal/test/mutator/opaque.proto

package mutator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpaqueMessage is an opaque API message used to verify that the mutator
// generator is correctly skipped. The opaque struct representation used by
// protoc-gen-go for editions files makes the SetXxx methods it generates
// conflict with any SetXxx that primo would produce, so primo skips them.
type OpaqueMessage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Num         int32                  `protobuf:"varint,1,opt,name=num"`
	xxx_hidden_Str         *string                `protobuf:"bytes,2,opt,name=str"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OpaqueMessage) Reset() {
	*x = OpaqueMessage{}
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueMessage) ProtoMessage() {}

func (x *OpaqueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpaqueMessage) GetNum() int32 {
	if x != nil {
		return x.xxx_hidden_Num
	}
	return 0
}

func (x *OpaqueMessage) GetStr() string {
	if x != nil {
		if x.xxx_hidden_Str != nil {
			return *x.xxx_hidden_Str
		}
		return ""
	}
	return ""
}

func (x *OpaqueMessage) SetNum(v int32) {
	x.xxx_hidden_Num = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OpaqueMessage) SetStr(v string) {
	x.xxx_hidden_Str = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *OpaqueMessage) HasNum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpaqueMessage) HasStr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OpaqueMessage) ClearNum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Num = 0
}

func (x *OpaqueMessage) ClearStr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Str = nil
}

type OpaqueMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Num *int32
	Str *string
}

func (b0 OpaqueMessage_builder) Build() *OpaqueMessage {
	m0 := &OpaqueMessage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Num != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Num = *b.Num
	}
	if b.Str != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Str = b.Str
	}
	return m0
}

var File_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_rawDesc = "" +
	"\n" +
	"<github.com/dogmatiq/primo/internal/test/mutator/opaque.proto\x12\x13primo.test.mutators\"3\n" +
	"\rOpaqueMessage\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\x12\x10\n" +
	"\x03str\x18\x02 \x01(\tR\x03strB1Z/github.com/dogmatiq/primo/internal/test/mutatorb\beditionsp\xe9\a"

var file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_goTypes = []any{
	(*OpaqueMessage)(nil), // 0: primo.test.mutators.OpaqueMessage
}
var file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_mutator_opaque_proto_depIdxs = nil
}
