// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/dogmatiq/primo/internal/test/mutator/proto3optional.proto

package mutator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proto3OptionalStatus int32

const (
	Proto3OptionalStatus_PROTO3_OPTIONAL_STATUS_UNSPECIFIED Proto3OptionalStatus = 0
	Proto3OptionalStatus_PROTO3_OPTIONAL_STATUS_OK          Proto3OptionalStatus = 1
	Proto3OptionalStatus_PROTO3_OPTIONAL_STATUS_ERR         Proto3OptionalStatus = 2
)

// Enum value maps for Proto3OptionalStatus.
var (
	Proto3OptionalStatus_name = map[int32]string{
		0: "PROTO3_OPTIONAL_STATUS_UNSPECIFIED",
		1: "PROTO3_OPTIONAL_STATUS_OK",
		2: "PROTO3_OPTIONAL_STATUS_ERR",
	}
	Proto3OptionalStatus_value = map[string]int32{
		"PROTO3_OPTIONAL_STATUS_UNSPECIFIED": 0,
		"PROTO3_OPTIONAL_STATUS_OK":          1,
		"PROTO3_OPTIONAL_STATUS_ERR":         2,
	}
)

func (x Proto3OptionalStatus) Enum() *Proto3OptionalStatus {
	p := new(Proto3OptionalStatus)
	*p = x
	return p
}

func (x Proto3OptionalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Proto3OptionalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_enumTypes[0].Descriptor()
}

func (Proto3OptionalStatus) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_enumTypes[0]
}

func (x Proto3OptionalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Proto3OptionalStatus.Descriptor instead.
func (Proto3OptionalStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescGZIP(), []int{0}
}

// Proto3OptionalMessage contains a mix of proto3 optional fields and a real
// oneof, to verify that optional fields are not misidentified as oneof members
// by the mutator generator.
type Proto3OptionalMessage struct {
	state  protoimpl.MessageState                     `protogen:"open.v1"`
	Num    *int32                                     `protobuf:"varint,1,opt,name=num,proto3,oneof" json:"num,omitempty"`
	Str    *string                                    `protobuf:"bytes,2,opt,name=str,proto3,oneof" json:"str,omitempty"`
	Flag   *bool                                      `protobuf:"varint,3,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	Status *Proto3OptionalStatus                      `protobuf:"varint,4,opt,name=status,proto3,enum=primo.test.mutator.Proto3OptionalStatus,oneof" json:"status,omitempty"`
	Child  *Proto3OptionalMessage_Proto3OptionalChild `protobuf:"bytes,5,opt,name=child,proto3,oneof" json:"child,omitempty"`
	// Types that are valid to be assigned to Choice:
	//
	//	*Proto3OptionalMessage_ChoiceA
	//	*Proto3OptionalMessage_ChoiceB
	Choice        isProto3OptionalMessage_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto3OptionalMessage) Reset() {
	*x = Proto3OptionalMessage{}
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto3OptionalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto3OptionalMessage) ProtoMessage() {}

func (x *Proto3OptionalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto3OptionalMessage.ProtoReflect.Descriptor instead.
func (*Proto3OptionalMessage) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescGZIP(), []int{0}
}

func (x *Proto3OptionalMessage) GetNum() int32 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

func (x *Proto3OptionalMessage) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return ""
}

func (x *Proto3OptionalMessage) GetFlag() bool {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return false
}

func (x *Proto3OptionalMessage) GetStatus() Proto3OptionalStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Proto3OptionalStatus_PROTO3_OPTIONAL_STATUS_UNSPECIFIED
}

func (x *Proto3OptionalMessage) GetChild() *Proto3OptionalMessage_Proto3OptionalChild {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *Proto3OptionalMessage) GetChoice() isProto3OptionalMessage_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *Proto3OptionalMessage) GetChoiceA() string {
	if x != nil {
		if x, ok := x.Choice.(*Proto3OptionalMessage_ChoiceA); ok {
			return x.ChoiceA
		}
	}
	return ""
}

func (x *Proto3OptionalMessage) GetChoiceB() int32 {
	if x != nil {
		if x, ok := x.Choice.(*Proto3OptionalMessage_ChoiceB); ok {
			return x.ChoiceB
		}
	}
	return 0
}

type isProto3OptionalMessage_Choice interface {
	isProto3OptionalMessage_Choice()
}

type Proto3OptionalMessage_ChoiceA struct {
	ChoiceA string `protobuf:"bytes,6,opt,name=choice_a,json=choiceA,proto3,oneof"`
}

type Proto3OptionalMessage_ChoiceB struct {
	ChoiceB int32 `protobuf:"varint,7,opt,name=choice_b,json=choiceB,proto3,oneof"`
}

func (*Proto3OptionalMessage_ChoiceA) isProto3OptionalMessage_Choice() {}

func (*Proto3OptionalMessage_ChoiceB) isProto3OptionalMessage_Choice() {}

type Proto3OptionalMessage_Proto3OptionalChild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto3OptionalMessage_Proto3OptionalChild) Reset() {
	*x = Proto3OptionalMessage_Proto3OptionalChild{}
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto3OptionalMessage_Proto3OptionalChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto3OptionalMessage_Proto3OptionalChild) ProtoMessage() {}

func (x *Proto3OptionalMessage_Proto3OptionalChild) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto3OptionalMessage_Proto3OptionalChild.ProtoReflect.Descriptor instead.
func (*Proto3OptionalMessage_Proto3OptionalChild) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescGZIP(), []int{0, 0}
}

var File_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDesc = "" +
	"\n" +
	"Dgithub.com/dogmatiq/primo/internal/test/mutator/proto3optional.proto\x12\x12primo.test.mutator\"\x88\x03\n" +
	"\x15Proto3OptionalMessage\x12\x15\n" +
	"\x03num\x18\x01 \x01(\x05H\x01R\x03num\x88\x01\x01\x12\x15\n" +
	"\x03str\x18\x02 \x01(\tH\x02R\x03str\x88\x01\x01\x12\x17\n" +
	"\x04flag\x18\x03 \x01(\bH\x03R\x04flag\x88\x01\x01\x12E\n" +
	"\x06status\x18\x04 \x01(\x0e2(.primo.test.mutator.Proto3OptionalStatusH\x04R\x06status\x88\x01\x01\x12X\n" +
	"\x05child\x18\x05 \x01(\v2=.primo.test.mutator.Proto3OptionalMessage.Proto3OptionalChildH\x05R\x05child\x88\x01\x01\x12\x1b\n" +
	"\bchoice_a\x18\x06 \x01(\tH\x00R\achoiceA\x12\x1b\n" +
	"\bchoice_b\x18\a \x01(\x05H\x00R\achoiceB\x1a\x15\n" +
	"\x13Proto3OptionalChildB\b\n" +
	"\x06choiceB\x06\n" +
	"\x04_numB\x06\n" +
	"\x04_strB\a\n" +
	"\x05_flagB\t\n" +
	"\a_statusB\b\n" +
	"\x06_child*}\n" +
	"\x14Proto3OptionalStatus\x12&\n" +
	"\"PROTO3_OPTIONAL_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PROTO3_OPTIONAL_STATUS_OK\x10\x01\x12\x1e\n" +
	"\x1aPROTO3_OPTIONAL_STATUS_ERR\x10\x02B1Z/github.com/dogmatiq/primo/internal/test/mutatorb\x06proto3"

var (
	file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescData []byte
)

func file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_goTypes = []any{
	(Proto3OptionalStatus)(0),                         // 0: primo.test.mutator.Proto3OptionalStatus
	(*Proto3OptionalMessage)(nil),                     // 1: primo.test.mutator.Proto3OptionalMessage
	(*Proto3OptionalMessage_Proto3OptionalChild)(nil), // 2: primo.test.mutator.Proto3OptionalMessage.Proto3OptionalChild
}
var file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_depIdxs = []int32{
	0, // 0: primo.test.mutator.Proto3OptionalMessage.status:type_name -> primo.test.mutator.Proto3OptionalStatus
	2, // 1: primo.test.mutator.Proto3OptionalMessage.child:type_name -> primo.test.mutator.Proto3OptionalMessage.Proto3OptionalChild
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto != nil {
		return
	}
	file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_msgTypes[0].OneofWrappers = []any{
		(*Proto3OptionalMessage_ChoiceA)(nil),
		(*Proto3OptionalMessage_ChoiceB)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_mutator_proto3optional_proto_depIdxs = nil
}
