// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: github.com/dogmatiq/primo/internal/test/mutator/scalar.proto

package mutator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scalar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32         int32                  `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64         int64                  `protobuf:"varint,2,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32        uint32                 `protobuf:"varint,3,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64        uint64                 `protobuf:"varint,4,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32        int32                  `protobuf:"zigzag32,5,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64        int64                  `protobuf:"zigzag64,6,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32       uint32                 `protobuf:"fixed32,7,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64       uint64                 `protobuf:"fixed64,8,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32      int32                  `protobuf:"fixed32,9,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64      int64                  `protobuf:"fixed64,10,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Float         float32                `protobuf:"fixed32,11,opt,name=float,proto3" json:"float,omitempty"`
	Double        float64                `protobuf:"fixed64,12,opt,name=double,proto3" json:"double,omitempty"`
	Bool          bool                   `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"`
	String_       string                 `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalar) Reset() {
	*x = Scalar{}
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalar) ProtoMessage() {}

func (x *Scalar) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalar.ProtoReflect.Descriptor instead.
func (*Scalar) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDescGZIP(), []int{0}
}

func (x *Scalar) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Scalar) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Scalar) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Scalar) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Scalar) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *Scalar) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *Scalar) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *Scalar) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *Scalar) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *Scalar) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *Scalar) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *Scalar) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *Scalar) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Scalar) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *Scalar) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

var File_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDesc = "" +
	"\n" +
	"<github.com/dogmatiq/primo/internal/test/mutator/scalar.proto\x12\x13primo.test.mutators\"\xf0\x02\n" +
	"\x06Scalar\x12\x14\n" +
	"\x05int32\x18\x01 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x02 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06uint32\x18\x03 \x01(\rR\x06uint32\x12\x16\n" +
	"\x06uint64\x18\x04 \x01(\x04R\x06uint64\x12\x16\n" +
	"\x06sint32\x18\x05 \x01(\x11R\x06sint32\x12\x16\n" +
	"\x06sint64\x18\x06 \x01(\x12R\x06sint64\x12\x18\n" +
	"\afixed32\x18\a \x01(\aR\afixed32\x12\x18\n" +
	"\afixed64\x18\b \x01(\x06R\afixed64\x12\x1a\n" +
	"\bsfixed32\x18\t \x01(\x0fR\bsfixed32\x12\x1a\n" +
	"\bsfixed64\x18\n" +
	" \x01(\x10R\bsfixed64\x12\x14\n" +
	"\x05float\x18\v \x01(\x02R\x05float\x12\x16\n" +
	"\x06double\x18\f \x01(\x01R\x06double\x12\x12\n" +
	"\x04bool\x18\r \x01(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\x0e \x01(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\x0f \x01(\fR\x05bytesB1Z/github.com/dogmatiq/primo/internal/test/mutatorb\x06proto3"

var (
	file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDescData []byte
)

func file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_goTypes = []any{
	(*Scalar)(nil), // 0: primo.test.mutators.Scalar
}
var file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_mutator_scalar_proto_depIdxs = nil
}
