// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: github.com/dogmatiq/primo/internal/test/mutator/userdefined.proto

package mutator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDefinedEnum int32

const (
	UserDefinedEnum_UNKNOWN UserDefinedEnum = 0
	UserDefinedEnum_VALUE   UserDefinedEnum = 1
)

// Enum value maps for UserDefinedEnum.
var (
	UserDefinedEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "VALUE",
	}
	UserDefinedEnum_value = map[string]int32{
		"UNKNOWN": 0,
		"VALUE":   1,
	}
)

func (x UserDefinedEnum) Enum() *UserDefinedEnum {
	p := new(UserDefinedEnum)
	*p = x
	return p
}

func (x UserDefinedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserDefinedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_enumTypes[0].Descriptor()
}

func (UserDefinedEnum) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_enumTypes[0]
}

func (x UserDefinedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserDefinedEnum.Descriptor instead.
func (UserDefinedEnum) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescGZIP(), []int{0}
}

type UserDefinedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDefinedMessage) Reset() {
	*x = UserDefinedMessage{}
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDefinedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDefinedMessage) ProtoMessage() {}

func (x *UserDefinedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDefinedMessage.ProtoReflect.Descriptor instead.
func (*UserDefinedMessage) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescGZIP(), []int{0}
}

type UserDefined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *UserDefinedMessage    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Enum          UserDefinedEnum        `protobuf:"varint,2,opt,name=enum,proto3,enum=primo.test.mutators.UserDefinedEnum" json:"enum,omitempty"`
	Nested        *UserDefined_Nested    `protobuf:"bytes,3,opt,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDefined) Reset() {
	*x = UserDefined{}
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDefined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDefined) ProtoMessage() {}

func (x *UserDefined) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDefined.ProtoReflect.Descriptor instead.
func (*UserDefined) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescGZIP(), []int{1}
}

func (x *UserDefined) GetMessage() *UserDefinedMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *UserDefined) GetEnum() UserDefinedEnum {
	if x != nil {
		return x.Enum
	}
	return UserDefinedEnum_UNKNOWN
}

func (x *UserDefined) GetNested() *UserDefined_Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

type UserDefined_Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDefined_Nested) Reset() {
	*x = UserDefined_Nested{}
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDefined_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDefined_Nested) ProtoMessage() {}

func (x *UserDefined_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDefined_Nested.ProtoReflect.Descriptor instead.
func (*UserDefined_Nested) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescGZIP(), []int{1, 0}
}

var File_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDesc = "" +
	"\n" +
	"Agithub.com/dogmatiq/primo/internal/test/mutator/userdefined.proto\x12\x13primo.test.mutators\"\x14\n" +
	"\x12UserDefinedMessage\"\xd5\x01\n" +
	"\vUserDefined\x12A\n" +
	"\amessage\x18\x01 \x01(\v2'.primo.test.mutators.UserDefinedMessageR\amessage\x128\n" +
	"\x04enum\x18\x02 \x01(\x0e2$.primo.test.mutators.UserDefinedEnumR\x04enum\x12?\n" +
	"\x06nested\x18\x03 \x01(\v2'.primo.test.mutators.UserDefined.NestedR\x06nested\x1a\b\n" +
	"\x06Nested*)\n" +
	"\x0fUserDefinedEnum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05VALUE\x10\x01B1Z/github.com/dogmatiq/primo/internal/test/mutatorb\x06proto3"

var (
	file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescData []byte
)

func file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDescData
}

var file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_goTypes = []any{
	(UserDefinedEnum)(0),       // 0: primo.test.mutators.UserDefinedEnum
	(*UserDefinedMessage)(nil), // 1: primo.test.mutators.UserDefinedMessage
	(*UserDefined)(nil),        // 2: primo.test.mutators.UserDefined
	(*UserDefined_Nested)(nil), // 3: primo.test.mutators.UserDefined.Nested
}
var file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_depIdxs = []int32{
	1, // 0: primo.test.mutators.UserDefined.message:type_name -> primo.test.mutators.UserDefinedMessage
	0, // 1: primo.test.mutators.UserDefined.enum:type_name -> primo.test.mutators.UserDefinedEnum
	3, // 2: primo.test.mutators.UserDefined.nested:type_name -> primo.test.mutators.UserDefined.Nested
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_init() }
func file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_init() {
	if File_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDesc), len(file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto = out.File
	file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_goTypes = nil
	file_github_com_dogmatiq_primo_internal_test_mutator_userdefined_proto_depIdxs = nil
}
