package accessor

import (
	"github.com/dave/jennifer/jen"
	"github.com/dogmatiq/primo/internal/generator/internal/scope"
)

// Generate generates accessor methods for each type in one-of group. In
// contrast to already available accessor methods generated by "protoc-gen-go"
// plugin, these accessor methods return a boolean value indicating whether the
// value is present or not.
func Generate(code *jen.File, f *scope.File) error {
	for _, m := range f.Messages() {
		for _, g := range m.OneOfGroups() {
			generateForOneOf(code, g)
		}
	}

	return nil
}
